SERVICE_NAME = gobierno
PROTO_FILE = proto/interaccion.proto
DOCKER_IMAGE = $(SERVICE_NAME)-image
DOCKER_CONTAINER = $(SERVICE_NAME)-container
PORT = 50052

docker-$(SERVICE_NAME): clean proto build docker-clean docker-build docker-run

proto:
    protoc --go_out=. --go-grpc_out=. $(PROTO_FILE)

build:
    go build -o $(SERVICE_NAME) .

docker-build:
    docker build -t $(DOCKER_IMAGE) .

docker-run:
    docker run -d -p $(PORT):$(PORT) --name $(DOCKER_CONTAINER) $(DOCKER_IMAGE)

docker-clean:
    docker stop $(DOCKER_CONTAINER) || true
    docker rm $(DOCKER_CONTAINER) || true

clean:
    rm -f $(SERVICE_NAME)
    rm -f proto/*.pb.go