// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: interaccion.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_interaccion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_interaccion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_interaccion_proto_rawDescGZIP(), []int{0}
}

type Pirata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre            string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Recompensa        int32                  `protobuf:"varint,3,opt,name=recompensa,proto3" json:"recompensa,omitempty"`
	NivelPeligrosidad string                 `protobuf:"bytes,4,opt,name=nivel_peligrosidad,json=nivelPeligrosidad,proto3" json:"nivel_peligrosidad,omitempty"`
	Estado            string                 `protobuf:"bytes,5,opt,name=estado,proto3" json:"estado,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Pirata) Reset() {
	*x = Pirata{}
	mi := &file_interaccion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pirata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pirata) ProtoMessage() {}

func (x *Pirata) ProtoReflect() protoreflect.Message {
	mi := &file_interaccion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pirata.ProtoReflect.Descriptor instead.
func (*Pirata) Descriptor() ([]byte, []int) {
	return file_interaccion_proto_rawDescGZIP(), []int{1}
}

func (x *Pirata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pirata) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Pirata) GetRecompensa() int32 {
	if x != nil {
		return x.Recompensa
	}
	return 0
}

func (x *Pirata) GetNivelPeligrosidad() string {
	if x != nil {
		return x.NivelPeligrosidad
	}
	return ""
}

func (x *Pirata) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type ListaPiratas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piratas       []*Pirata              `protobuf:"bytes,1,rep,name=piratas,proto3" json:"piratas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaPiratas) Reset() {
	*x = ListaPiratas{}
	mi := &file_interaccion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaPiratas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaPiratas) ProtoMessage() {}

func (x *ListaPiratas) ProtoReflect() protoreflect.Message {
	mi := &file_interaccion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaPiratas.ProtoReflect.Descriptor instead.
func (*ListaPiratas) Descriptor() ([]byte, []int) {
	return file_interaccion_proto_rawDescGZIP(), []int{2}
}

func (x *ListaPiratas) GetPiratas() []*Pirata {
	if x != nil {
		return x.Piratas
	}
	return nil
}

type EntregaRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdPirata           string                 `protobuf:"bytes,1,opt,name=id_pirata,json=idPirata,proto3" json:"id_pirata,omitempty"`
	Destino            string                 `protobuf:"bytes,2,opt,name=destino,proto3" json:"destino,omitempty"`
	CazarrecompensasId string                 `protobuf:"bytes,3,opt,name=cazarrecompensas_id,json=cazarrecompensasId,proto3" json:"cazarrecompensas_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EntregaRequest) Reset() {
	*x = EntregaRequest{}
	mi := &file_interaccion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntregaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntregaRequest) ProtoMessage() {}

func (x *EntregaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaccion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntregaRequest.ProtoReflect.Descriptor instead.
func (*EntregaRequest) Descriptor() ([]byte, []int) {
	return file_interaccion_proto_rawDescGZIP(), []int{3}
}

func (x *EntregaRequest) GetIdPirata() string {
	if x != nil {
		return x.IdPirata
	}
	return ""
}

func (x *EntregaRequest) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *EntregaRequest) GetCazarrecompensasId() string {
	if x != nil {
		return x.CazarrecompensasId
	}
	return ""
}

type EntregaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Recompensa    int32                  `protobuf:"varint,3,opt,name=recompensa,proto3" json:"recompensa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntregaResponse) Reset() {
	*x = EntregaResponse{}
	mi := &file_interaccion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntregaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntregaResponse) ProtoMessage() {}

func (x *EntregaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaccion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntregaResponse.ProtoReflect.Descriptor instead.
func (*EntregaResponse) Descriptor() ([]byte, []int) {
	return file_interaccion_proto_rawDescGZIP(), []int{4}
}

func (x *EntregaResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *EntregaResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *EntregaResponse) GetRecompensa() int32 {
	if x != nil {
		return x.Recompensa
	}
	return 0
}

type RedadaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedadaRequest) Reset() {
	*x = RedadaRequest{}
	mi := &file_interaccion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedadaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedadaRequest) ProtoMessage() {}

func (x *RedadaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaccion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedadaRequest.ProtoReflect.Descriptor instead.
func (*RedadaRequest) Descriptor() ([]byte, []int) {
	return file_interaccion_proto_rawDescGZIP(), []int{5}
}

func (x *RedadaRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type RedadaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedadaResponse) Reset() {
	*x = RedadaResponse{}
	mi := &file_interaccion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedadaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedadaResponse) ProtoMessage() {}

func (x *RedadaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaccion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedadaResponse.ProtoReflect.Descriptor instead.
func (*RedadaResponse) Descriptor() ([]byte, []int) {
	return file_interaccion_proto_rawDescGZIP(), []int{6}
}

func (x *RedadaResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *RedadaResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type ReputacionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CazarrecompensasId string                 `protobuf:"bytes,1,opt,name=cazarrecompensas_id,json=cazarrecompensasId,proto3" json:"cazarrecompensas_id,omitempty"`
	Cambio             int32                  `protobuf:"varint,2,opt,name=cambio,proto3" json:"cambio,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReputacionRequest) Reset() {
	*x = ReputacionRequest{}
	mi := &file_interaccion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReputacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReputacionRequest) ProtoMessage() {}

func (x *ReputacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaccion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReputacionRequest.ProtoReflect.Descriptor instead.
func (*ReputacionRequest) Descriptor() ([]byte, []int) {
	return file_interaccion_proto_rawDescGZIP(), []int{7}
}

func (x *ReputacionRequest) GetCazarrecompensasId() string {
	if x != nil {
		return x.CazarrecompensasId
	}
	return ""
}

func (x *ReputacionRequest) GetCambio() int32 {
	if x != nil {
		return x.Cambio
	}
	return 0
}

type ReputacionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReputacionResponse) Reset() {
	*x = ReputacionResponse{}
	mi := &file_interaccion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReputacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReputacionResponse) ProtoMessage() {}

func (x *ReputacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaccion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReputacionResponse.ProtoReflect.Descriptor instead.
func (*ReputacionResponse) Descriptor() ([]byte, []int) {
	return file_interaccion_proto_rawDescGZIP(), []int{8}
}

func (x *ReputacionResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ReputacionResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type AlertaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertaRequest) Reset() {
	*x = AlertaRequest{}
	mi := &file_interaccion_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertaRequest) ProtoMessage() {}

func (x *AlertaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaccion_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertaRequest.ProtoReflect.Descriptor instead.
func (*AlertaRequest) Descriptor() ([]byte, []int) {
	return file_interaccion_proto_rawDescGZIP(), []int{9}
}

func (x *AlertaRequest) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type AlertaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertaResponse) Reset() {
	*x = AlertaResponse{}
	mi := &file_interaccion_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertaResponse) ProtoMessage() {}

func (x *AlertaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaccion_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertaResponse.ProtoReflect.Descriptor instead.
func (*AlertaResponse) Descriptor() ([]byte, []int) {
	return file_interaccion_proto_rawDescGZIP(), []int{10}
}

func (x *AlertaResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *AlertaResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type TransporteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdPirata      string                 `protobuf:"bytes,1,opt,name=id_pirata,json=idPirata,proto3" json:"id_pirata,omitempty"`
	Destino       string                 `protobuf:"bytes,2,opt,name=destino,proto3" json:"destino,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransporteRequest) Reset() {
	*x = TransporteRequest{}
	mi := &file_interaccion_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransporteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransporteRequest) ProtoMessage() {}

func (x *TransporteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaccion_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransporteRequest.ProtoReflect.Descriptor instead.
func (*TransporteRequest) Descriptor() ([]byte, []int) {
	return file_interaccion_proto_rawDescGZIP(), []int{11}
}

func (x *TransporteRequest) GetIdPirata() string {
	if x != nil {
		return x.IdPirata
	}
	return ""
}

func (x *TransporteRequest) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

type TransporteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransporteResponse) Reset() {
	*x = TransporteResponse{}
	mi := &file_interaccion_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransporteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransporteResponse) ProtoMessage() {}

func (x *TransporteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaccion_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransporteResponse.ProtoReflect.Descriptor instead.
func (*TransporteResponse) Descriptor() ([]byte, []int) {
	return file_interaccion_proto_rawDescGZIP(), []int{12}
}

func (x *TransporteResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *TransporteResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_interaccion_proto protoreflect.FileDescriptor

const file_interaccion_proto_rawDesc = "" +
	"\n" +
	"\x11interaccion.proto\x12\vinteraccion\"\a\n" +
	"\x05Empty\"\x97\x01\n" +
	"\x06Pirata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1e\n" +
	"\n" +
	"recompensa\x18\x03 \x01(\x05R\n" +
	"recompensa\x12-\n" +
	"\x12nivel_peligrosidad\x18\x04 \x01(\tR\x11nivelPeligrosidad\x12\x16\n" +
	"\x06estado\x18\x05 \x01(\tR\x06estado\"=\n" +
	"\fListaPiratas\x12-\n" +
	"\apiratas\x18\x01 \x03(\v2\x13.interaccion.PirataR\apiratas\"x\n" +
	"\x0eEntregaRequest\x12\x1b\n" +
	"\tid_pirata\x18\x01 \x01(\tR\bidPirata\x12\x18\n" +
	"\adestino\x18\x02 \x01(\tR\adestino\x12/\n" +
	"\x13cazarrecompensas_id\x18\x03 \x01(\tR\x12cazarrecompensasId\"a\n" +
	"\x0fEntregaResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12\x1e\n" +
	"\n" +
	"recompensa\x18\x03 \x01(\x05R\n" +
	"recompensa\"'\n" +
	"\rRedadaRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\"@\n" +
	"\x0eRedadaResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"\\\n" +
	"\x11ReputacionRequest\x12/\n" +
	"\x13cazarrecompensas_id\x18\x01 \x01(\tR\x12cazarrecompensasId\x12\x16\n" +
	"\x06cambio\x18\x02 \x01(\x05R\x06cambio\"D\n" +
	"\x12ReputacionResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\")\n" +
	"\rAlertaRequest\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\"@\n" +
	"\x0eAlertaResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"J\n" +
	"\x11TransporteRequest\x12\x1b\n" +
	"\tid_pirata\x18\x01 \x01(\tR\bidPirata\x12\x18\n" +
	"\adestino\x18\x02 \x01(\tR\adestino\"D\n" +
	"\x12TransporteResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje2\xce\x02\n" +
	"\x17CazarrecompensasService\x12A\n" +
	"\x10ConsultarPiratas\x12\x12.interaccion.Empty\x1a\x19.interaccion.ListaPiratas\x12M\n" +
	"\x10RegistrarCaptura\x12\x1b.interaccion.EntregaRequest\x1a\x1c.interaccion.EntregaResponse\x12K\n" +
	"\x0eDecidirEntrega\x12\x1b.interaccion.EntregaRequest\x1a\x1c.interaccion.EntregaResponse\x12T\n" +
	"\x11TransportarPirata\x12\x1e.interaccion.TransporteRequest\x1a\x1f.interaccion.TransporteResponse2\xa6\x01\n" +
	"\rMarinaService\x12J\n" +
	"\rRecibirPirata\x12\x1b.interaccion.EntregaRequest\x1a\x1c.interaccion.EntregaResponse\x12I\n" +
	"\x0eRealizarRedada\x12\x1a.interaccion.RedadaRequest\x1a\x1b.interaccion.RedadaResponse2\xac\x01\n" +
	"\x0fSubmundoService\x12J\n" +
	"\rComprarPirata\x12\x1b.interaccion.EntregaRequest\x1a\x1c.interaccion.EntregaResponse\x12M\n" +
	"\x11EnviarMercenarios\x12\x1b.interaccion.EntregaRequest\x1a\x1b.interaccion.RedadaResponse2\xc9\x02\n" +
	"\x0fGobiernoService\x12E\n" +
	"\x14PublicarListaPiratas\x12\x12.interaccion.Empty\x1a\x19.interaccion.ListaPiratas\x12M\n" +
	"\x10RegistrarCaptura\x12\x1b.interaccion.EntregaRequest\x1a\x1c.interaccion.EntregaResponse\x12W\n" +
	"\x14ActualizarReputacion\x12\x1e.interaccion.ReputacionRequest\x1a\x1f.interaccion.ReputacionResponse\x12G\n" +
	"\fEmitirAlerta\x12\x1a.interaccion.AlertaRequest\x1a\x1b.interaccion.AlertaResponseB\x13Z\x11grpc-server/protob\x06proto3"

var (
	file_interaccion_proto_rawDescOnce sync.Once
	file_interaccion_proto_rawDescData []byte
)

func file_interaccion_proto_rawDescGZIP() []byte {
	file_interaccion_proto_rawDescOnce.Do(func() {
		file_interaccion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interaccion_proto_rawDesc), len(file_interaccion_proto_rawDesc)))
	})
	return file_interaccion_proto_rawDescData
}

var file_interaccion_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_interaccion_proto_goTypes = []any{
	(*Empty)(nil),              // 0: interaccion.Empty
	(*Pirata)(nil),             // 1: interaccion.Pirata
	(*ListaPiratas)(nil),       // 2: interaccion.ListaPiratas
	(*EntregaRequest)(nil),     // 3: interaccion.EntregaRequest
	(*EntregaResponse)(nil),    // 4: interaccion.EntregaResponse
	(*RedadaRequest)(nil),      // 5: interaccion.RedadaRequest
	(*RedadaResponse)(nil),     // 6: interaccion.RedadaResponse
	(*ReputacionRequest)(nil),  // 7: interaccion.ReputacionRequest
	(*ReputacionResponse)(nil), // 8: interaccion.ReputacionResponse
	(*AlertaRequest)(nil),      // 9: interaccion.AlertaRequest
	(*AlertaResponse)(nil),     // 10: interaccion.AlertaResponse
	(*TransporteRequest)(nil),  // 11: interaccion.TransporteRequest
	(*TransporteResponse)(nil), // 12: interaccion.TransporteResponse
}
var file_interaccion_proto_depIdxs = []int32{
	1,  // 0: interaccion.ListaPiratas.piratas:type_name -> interaccion.Pirata
	0,  // 1: interaccion.CazarrecompensasService.ConsultarPiratas:input_type -> interaccion.Empty
	3,  // 2: interaccion.CazarrecompensasService.RegistrarCaptura:input_type -> interaccion.EntregaRequest
	3,  // 3: interaccion.CazarrecompensasService.DecidirEntrega:input_type -> interaccion.EntregaRequest
	11, // 4: interaccion.CazarrecompensasService.TransportarPirata:input_type -> interaccion.TransporteRequest
	3,  // 5: interaccion.MarinaService.RecibirPirata:input_type -> interaccion.EntregaRequest
	5,  // 6: interaccion.MarinaService.RealizarRedada:input_type -> interaccion.RedadaRequest
	3,  // 7: interaccion.SubmundoService.ComprarPirata:input_type -> interaccion.EntregaRequest
	3,  // 8: interaccion.SubmundoService.EnviarMercenarios:input_type -> interaccion.EntregaRequest
	0,  // 9: interaccion.GobiernoService.PublicarListaPiratas:input_type -> interaccion.Empty
	3,  // 10: interaccion.GobiernoService.RegistrarCaptura:input_type -> interaccion.EntregaRequest
	7,  // 11: interaccion.GobiernoService.ActualizarReputacion:input_type -> interaccion.ReputacionRequest
	9,  // 12: interaccion.GobiernoService.EmitirAlerta:input_type -> interaccion.AlertaRequest
	2,  // 13: interaccion.CazarrecompensasService.ConsultarPiratas:output_type -> interaccion.ListaPiratas
	4,  // 14: interaccion.CazarrecompensasService.RegistrarCaptura:output_type -> interaccion.EntregaResponse
	4,  // 15: interaccion.CazarrecompensasService.DecidirEntrega:output_type -> interaccion.EntregaResponse
	12, // 16: interaccion.CazarrecompensasService.TransportarPirata:output_type -> interaccion.TransporteResponse
	4,  // 17: interaccion.MarinaService.RecibirPirata:output_type -> interaccion.EntregaResponse
	6,  // 18: interaccion.MarinaService.RealizarRedada:output_type -> interaccion.RedadaResponse
	4,  // 19: interaccion.SubmundoService.ComprarPirata:output_type -> interaccion.EntregaResponse
	6,  // 20: interaccion.SubmundoService.EnviarMercenarios:output_type -> interaccion.RedadaResponse
	2,  // 21: interaccion.GobiernoService.PublicarListaPiratas:output_type -> interaccion.ListaPiratas
	4,  // 22: interaccion.GobiernoService.RegistrarCaptura:output_type -> interaccion.EntregaResponse
	8,  // 23: interaccion.GobiernoService.ActualizarReputacion:output_type -> interaccion.ReputacionResponse
	10, // 24: interaccion.GobiernoService.EmitirAlerta:output_type -> interaccion.AlertaResponse
	13, // [13:25] is the sub-list for method output_type
	1,  // [1:13] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_interaccion_proto_init() }
func file_interaccion_proto_init() {
	if File_interaccion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interaccion_proto_rawDesc), len(file_interaccion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_interaccion_proto_goTypes,
		DependencyIndexes: file_interaccion_proto_depIdxs,
		MessageInfos:      file_interaccion_proto_msgTypes,
	}.Build()
	File_interaccion_proto = out.File
	file_interaccion_proto_goTypes = nil
	file_interaccion_proto_depIdxs = nil
}
